[package]
name = "lastfmrobot"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { git = "https://github.com/teloxide/teloxide.git", features = ["macros", "throttle"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.35.1", features = ["full"] }
reqwest = "0.11.23"
serde_json = "1.0.113"
rusqlite = { version = "0.30.0", features = ["bundled"] }
image = "0.24.8"
imageproc = "0.23.0"
rusttype = "0.9.3"
url-escape = "0.1.1"
http-cache-reqwest = { version = "0.13.0", features = ["manager-moka"] }
reqwest-middleware = "0.2.4"
num-format = "0.4.4"
bytes = "1.5.0"
serde = "1.0.196"
serde_with = "3.5.1"
timeago = "0.4.2"
rand = "0.8.5"
once_cell = "1.19.0"
async-trait = "0.1.77"
task-local-extensions = "0.1.4"
anyhow = "1.0.79"
moka = { version = "0.12.5", features = ["future"] }
strum = "0.26.1"
strum_macros = "0.26.1"
chrono = "0.4.33"
