[package]
name = "lastfmrobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { git = "https://github.com/teloxide/teloxide.git", features = ["macros", "throttle"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.33.0", features = ["full"] }
reqwest = "0.11.22"
serde_json = "1.0.107"
rusqlite = { version = "0.29.0", features = ["bundled"] }
image = "0.24.7"
imageproc = "0.23.0"
rusttype = "0.9.3"
url-escape = "0.1.1"
http-cache-reqwest = { version = "0.11.3", features = ["manager-moka"] }
reqwest-middleware = "0.2.4"
num-format = "0.4.4"
bytes = "1.5.0"
serde = "1.0.189"
serde_with = "3.4.0"
timeago = "0.4.2"
rand = "0.8.5"
once_cell = "1.18.0"
async-trait = "0.1.74"
task-local-extensions = "0.1.4"
anyhow = "1.0.75"
moka = { version = "0.12.1", features = ["future"] }
strum = "0.25.0"
strum_macros = "0.25"
chrono = "0.4.31"
